config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :users do
    get 'patients/register', to: 'patients/patient_registration#new', as: 'patient_registration'
    post 'patients/register', to: 'patients/patient_registration#create'

    get 'doctors/register', to: 'doctors/doctor_registration#new', as: 'doctor_registration'
    post 'doctors/register', to: 'doctors/doctor_registration#create'

    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :chat_messages
  resources :practices

  resources :doctors do
    get :search, on: :collection
  end

  resources :license_activations
  resources :prescriptions, controller: 'prescriptions'

  resources :patients do
    get :dashboard, to: 'patients#dashboard', as: 'dashboard'
    get :profile
    get :connect_with_doctor, to: 'patient_chat_rooms#connect_with_doctor'

    resources :chat_rooms do
      post :send_transcript, to: 'patient_chat_rooms#send_transcript'
      get :end_session, to: 'patient_chat_rooms#end_session'
    end
    resources :questions
    resources :transcripts, controller: 'patients/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'consultation_requests'
    resources :urgent_requests, controller: 'urgent_requests' do
      get :wait_screen
      get :check_for_session_start
    end
    root to: 'patients#index'
  end

  resources :doctors do
    get :dashboard, to: 'doctors#dashboard', as: 'dashboard'
    get :accept_urgent_request, to: 'doctors#accept_urgent_request', as: 'accept_urgent_request'
    get :profile
    get :connect_with_patient, to: 'doctor_chat_rooms#connect_with_patient'

    resources :chat_rooms do
      post :send_transcript, to: 'doctor_chat_rooms#send_transcript'
      get :end_session, to: 'doctor_chat_rooms#end_session'
    end
    resources :transcripts, controller: 'doctors/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'doctors/consultation_request'
    root to: 'doctors#index'
  end

  namespace :doctor do
    resources :answers
  end

  root to: 'static#index'
end

app/models/consultation_request.rb
class ConsultationRequest < Request
  belongs_to :directed_to, class_name: 'Doctor'
  has_one :chat_room, foreign_key: 'consultation_request_id'

  validates_length_of :description, minimum: 5, maximum: 1000
  scope :upcoming, -> { scheduled_for > Time.now }
  scope :past, -> { scheduled_for < Time.now }
end

app/controllers/consultation_requests_controller.rb
class ConsultationRequestsController < ApplicationController
  layout 'patients/patients'
  skip_before_action :verify_authenticity_token
  before_action :set_consultation_request, only: [:show, :edit, :update, :destroy]
  before_action :load_doctor, only: [:create, :update]
  before_action :load_date, only: [:create, :update]

  def index
    @upcoming_consultation_requests = ConsultationRequest.left_outer_joins(:chat_room).where(patient: current_user.patient, chat_rooms: { consultation_request_id: nil })
    @previous_consultation_requests = ConsultationRequest.where(patient: current_user.patient, status: :finished)
  end

  def show
  end

  def new
    @consultation_request = ConsultationRequest.new(patient: current_user.patient)
  end

  def create
    @consultation_request = ConsultationRequest.new(
      description: consultation_request_params['description'],
      patient: current_user.patient,
      directed_to: @doctor,
      scheduled_for: parsed_scheduled_for
    )
    if consultation_request_params['media'].present?
      @consultation_request.media.attach(consultation_request_params['media'])
    end

    if @consultation_request.save!
      respond_to do |format|
        format.html { redirect_to patient_consultation_request_path(id: @consultation_request), notice: 'Booking successful.' }
        format.json { render :show, status: :created, location: @consultation_request }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @consultation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if consultation_request_params['media'].present?
      @consultation_request.media.attach(consultation_request_params['media'])
    end

    if @consultation_request.update!(
      description: consultation_request_params['description'],
      patient: current_user.patient,
      directed_to: @doctor,
      scheduled_for: parsed_scheduled_for
    )
      respond_to do |format|
        format.html { redirect_to patient_consultation_request_path(id: @consultation_request), notice: 'Booking successful.' }
        format.json { render :show, status: :created, location: @consultation_request }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @consultation_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    redirect_to patient_consultation_requests_path if @consultation_request.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_consultation_request
    @consultation_request = ConsultationRequest.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def consultation_request_params
    params.require(:consultation_request).permit(:description, :directed_to_id, :scheduled_for, :media)
  end

  def load_doctor
    return unless consultation_request_params['directed_to_id'].present?

    @user = User.find_by(username: consultation_request_params['directed_to_id'])
    raise 'Could not find user' unless @user.present?

    @doctor = Doctor.find_by(user: @user)

    raise 'Could not find doctor' unless @doctor.present?
  end

  def load_date
    dt = parsed_scheduled_for

    raise 'Could not parse date' unless dt.present?

    return unless Time.now + 1.hour > parsed_scheduled_for

    respond_to do |format|
      @consultation_request = ConsultationRequest.new(patient: current_user.patient)
      format.html { render :new }
      format.json { render json: { error: 'You cannot earlier a consultation any ealier than 1 hour' }, status: :unprocessable_entity }
    end
  end

  def parsed_scheduled_for
    return unless consultation_request_params['scheduled_for(1i)'].present?

    DateTime.new(
      consultation_request_params['scheduled_for(1i)'].to_i,
      consultation_request_params['scheduled_for(2i)'].to_i,
      consultation_request_params['scheduled_for(3i)'].to_i,
      consultation_request_params['scheduled_for(4i)'].to_i,
      consultation_request_params['scheduled_for(5i)'].to_i
    )
  end
end

app/controllers/doctors/consultation_request_controller.rb
class Doctors::ConsultationRequestController < DoctorsController
  def show; end

  def index
    @upcoming_consultation_requests =
      ConsultationRequest
      .left_outer_joins(:chat_room)
      .where(chat_rooms: { doctor: current_user.doctor, consultation_request_id: nil })

    @previous_consulation_requests =
      ConsultationRequest
      .joins(:chat_room)
      .where(chat_rooms: { doctor: current_user.doctor} )
  end
end

app/helpers/consultation_requests_helper.rb
module ConsultationRequestsHelper
end

app/helpers/doctors/consultation_request_helper.rb
module Doctors::ConsultationRequestHelper
end

app/views/consultation_requests/_edit_form.haml
:coffee
  $ ->
    $('.custom-file input').change (e) ->
      files = []
      i = 0
      while i < $(this)[0].files.length
        files.push $(this)[0].files[i].name
        i++

      $(this).next('.custom-file-label').html files.join(', ')

= bootstrap_form_for @consultation_request, url: patient_consultation_request_path, method: 'PATCH', remote: true do |f|
  - if @consultation_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@consultation_request.errors.count, "error")} prohibited this consultation_request from being saved:"
      %ul
        - @consultation_request.errors.full_messages.each do |message|
          %li= message

  .field
    = f.text_area :description
  .field
    = f.collection_select :directed_to_id, Doctor.all, :id, :name
  .field
    = f.datetime_select :scheduled_for
  .field
    = f.file_field :media, required: false, label: 'Attachment'
    - if @consultation_request.media.attached?
      %i Current attachment
      = image_tag @consultation_request.media.variant(resize: "400x400")

  .actions
    = link_to 'Back', patient_consultation_requests_path, class: 'btn btn-danger'
    = f.submit 'Save', class: 'btn btn-success'

app/views/consultation_requests/_form.haml
:coffee
  $ ->
    currentSelectedRow = {}
  
    $('.custom-file input').change (e) ->
      files = []
      i = 0
      while i < $(this)[0].files.length
        files.push $(this)[0].files[i].name
        i++

      $(this).next('.custom-file-label').html files.join(', ')

    $('#doctors-datatable').dataTable
      processing: true
      serverSide: true
      ajax:
        url: $('#doctors-datatable').data('source')
      pagingType: 'full_numbers'
      language: { search: 'Search by any column:' }
      columns: [
        { data: 'license_number' }
        { data: 'name' }
        { data: 'practice' }
        { data: 'address' }
        { data: 'phone' }
      ]
      
    $('#doctors-datatable').on 'click', 'tbody tr', (e) ->
      columns = jQuery.makeArray(e.currentTarget.cells);
      currentSelectedRow = {}
      
      $.each columns, (index, column) ->
        currentSelectedRow[index] = column.textContent
        
      $('#consultation_request_directed_to_id').val(currentSelectedRow[1])
      
      $('input[type="submit"]').attr('disabled', false)
      

:sass
  #practiceSearch
    max-width: 500px

  .selectedDoctor
    max-width: 300px

= bootstrap_form_for @consultation_request, url: patient_consultation_requests_path do |f|
  - if @consultation_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@consultation_request.errors.count, "error")} prohibited this consultation_request from being saved:"
      %ul
        - @consultation_request.errors.full_messages.each do |message|
          %li= message

  .field
    = f.text_area :description, label: 'Description of your issue or questions'
  .field
    = f.datetime_select :scheduled_for
  .field
    = f.file_field :media, required: false, label: 'Attachment'
  .field
    = f.text_field :directed_to_id, label: 'Selected Doctor:', readonly: 'readonly', class: 'selectedDoctor'
  .actions
    = link_to 'Back', patient_consultation_requests_path, class: 'btn btn-danger'
    = f.submit 'Save', class: 'btn btn-success', disabled: true

%hr
%table.table.table-hover#doctors-datatable{'data-source': search_doctors_path(format: :json)}
  %caption#caption You can select a doctor by simply clicking on the row
  %thead
    %tr
      %th License No
      %th Name
      %th Practice
      %th Address
      %th Phone Number
  %tbody

app/views/consultation_requests/_previous.haml
%h3 Previous Consultations
%table.table.table-hover
  %thead
    %tr
      %th Description
      %th Doctor
      %th Scheduled for
      %th
  
  %tbody
    - @previous_consultation_requests.each do |consultation_request|
      %tr
        %td= consultation_request.description
        %td= consultation_request.directed_to.name
        %td= consultation_request.scheduled_for.strftime('%d/%m/%y: %H:%M %p')
        %td= link_to 'Show', patient_consultation_request_path(id: consultation_request)

app/views/consultation_requests/_upcoming.haml
%h3 Upcoming Consultations
%table.table.table-hover
  %thead
    %tr
      %th Description
      %th Doctor
      %th Scheduled for
      %th
  
  %tbody
    - @upcoming_consultation_requests.each do |consultation_request|
      %tr
        %td= consultation_request.description
        %td= consultation_request.directed_to.name
        %td= consultation_request.scheduled_for.strftime('%d/%m/%y: %H:%M %p')
        %td= link_to 'Show', patient_consultation_request_path(id: consultation_request)

app/views/consultation_requests/edit.haml
%h1 Editing this Consultation

= render 'edit_form'

app/views/consultation_requests/index.haml
- if @upcoming_consultation_requests.present?
  = render partial: 'upcoming'
- else
  %i You have no upcoming consultations
  %br

- if @previous_consultation_requests.present?
  = render partial: 'previous'
- else
  %i You have no past consultations
  %br

%br
= link_to 'Book a consultation', new_patient_consultation_request_path(current_user.patient)

app/views/consultation_requests/new.haml
%h1 Book a consultation

= render 'form'

app/views/consultation_requests/show.haml
%h3 About your consultation

%p
  %b Description:
  = @consultation_request.description
%p
  %b Directed to:
  = @consultation_request.directed_to.name
%p
  %b Scheduled for:
  = @consultation_request.scheduled_for.strftime('%d/%m/%y: %H:%M %p')
%p
  %b Attachment:
  - if @consultation_request.media.attached?
    = image_tag @consultation_request.media.variant(resize: "400x400")
  - else
    No attachments provided

= link_to 'Back', patient_consultation_requests_path(current_user.patient), class: 'btn btn-info'
- if @consultation_request.status == 'scheduled'
  = link_to 'Edit', edit_patient_consultation_request_path(id: @consultation_request), class: 'btn btn-primary'
  = link_to 'Cancel', patient_consultation_request_path(id: @consultation_request), method: :delete,
    data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
- elsif @consultation_request.status == 'finished'
  = link_to 'View transcript', patient_transcript_path(patient: current_user.patient, transcript_id: @consultation_request.chat_room.transcript&.id),
    class: 'btn btn-success'
- if !current_user.patient.in_session?
  = link_to 'Join session',
    patient_connect_with_doctor_path(consultation_request_id: @consultation_request.id), class: 'btn btn-success'