config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :users do
    get 'patients/register', to: 'patients/patient_registration#new', as: 'patient_registration'
    post 'patients/register', to: 'patients/patient_registration#create'

    get 'doctors/register', to: 'doctors/doctor_registration#new', as: 'doctor_registration'
    post 'doctors/register', to: 'doctors/doctor_registration#create'

    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :chat_messages
  resources :practices

  resources :doctors do
    get :search, on: :collection
  end

  resources :license_activations
  resources :prescriptions, controller: 'prescriptions'

  resources :patients do
    get :dashboard, to: 'patients#dashboard', as: 'dashboard'
    get :profile
    get :connect_with_doctor, to: 'patient_chat_rooms#connect_with_doctor'

    resources :chat_rooms do
      post :send_transcript, to: 'patient_chat_rooms#send_transcript'
      get :end_session, to: 'patient_chat_rooms#end_session'
    end
    resources :questions
    resources :transcripts, controller: 'patients/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'consultation_requests'
    resources :urgent_requests, controller: 'urgent_requests' do
      get :wait_screen
      get :check_for_session_start
    end
    root to: 'patients#index'
  end

  resources :doctors do
    get :dashboard, to: 'doctors#dashboard', as: 'dashboard'
    get :accept_urgent_request, to: 'doctors#accept_urgent_request', as: 'accept_urgent_request'
    get :profile
    get :connect_with_patient, to: 'doctor_chat_rooms#connect_with_patient'

    resources :chat_rooms do
      post :send_transcript, to: 'doctor_chat_rooms#send_transcript'
      get :end_session, to: 'doctor_chat_rooms#end_session'
    end
    resources :transcripts, controller: 'doctors/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'doctors/consultation_request'
    root to: 'doctors#index'
  end

  namespace :doctor do
    resources :answers
  end

  root to: 'static#index'
end

app/controllers/doctor_chat_rooms_controller.rb
class DoctorChatRoomsController < DoctorsController
  before_action :accept_all_params
  before_action :load_chat_room, only: %i[show send_transcript]

  # This action creates a chat_room associated to the request the user is navigating from
  def connect_with_patient
    redirect_to root_path unless params[:urgent_request_id].present? || params[:consultation_request_id].present?

    if params[:urgent_request_id].present?
      handle_urgent_request
    elsif params[:consultation_request_id].present?
      handle_consultation_request
    end
  end

  def send_transcript
    @transcript = Transcript.find_by(chat_room: @chat_room)
    @transcript = Transcript.create(chat_room: @chat_room) if @transcript.blank?

    TranscriptMailer.with(transcript: @transcript, send_to: 'doctor').chat_transcript.deliver_now

    render json: {}, status: :ok
  end

  def end_session
    @chat_room = ChatRoom.find(params[:chat_room_id])
    associated_request = @chat_room.urgent_request.presence || @chat_room.consultation_request
    associated_request.update(status: :finished)

    @transcript = Transcript.find_by(chat_room: @chat_room)
    @transcript = Transcript.create(chat_room: @chat_room) if @transcript.blank?

    ActionCable.server.broadcast "chat_room_channel_#{@chat_room.id}", action: 'end_session'
    redirect_to root_path
  end

  private

  def handle_urgent_request
    urgent_request = UrgentRequest.find_by(id: params[:urgent_request_id])
    # Need to check if it is in progress; if so we should just redirect the user
    # back to the homepage and say that the consultation is over
    @chat_room = ChatRoom.find_or_create_by(doctor: @doctor, urgent_request: urgent_request)
    set_up_chat_room

    render 'doctor_chat_rooms/show'
  end

  def handle_consultation_request
    consultation_request = ConsultationRequest.find_by(id: params[:consultation_request_id])
    # same as above
    @chat_room = ChatRoom.find_or_create_by(
      consultation_request: consultation_request,
      patient: consultation_request.patient,
      doctor: @doctor
    )
    set_up_chat_room

    render 'doctor_chat_rooms/show'
  end

  def set_up_chat_room
    @chat_room.request.update!(status: :in_progress)
    @chat_message = ChatMessage.new chat_room: @chat_room
    @chat_messages = @chat_room.chat_messages.includes(:user)
  end

  def load_chat_room
    @chat_room = ChatRoom.find(params[:id]) if params[:id]
  end

  def accept_all_params
    params.permit!
  end
end

app/views/doctor_chat_rooms/show.haml
:coffee
  $ ->
    scrollToBottom = ->
      $("#chat_messages").animate({ scrollTop: $("#chat_messages").prop('scrollHeight')}, 1000);
    scrollToBottom()

    $('form#new_chat_message').on 'submit', (e) ->
      msg = $('input#chat_message_message').val()
      chatRoomID = $('input#chat_message_chat_room_id').val()

      if msg != ''
        $.ajax
          type: 'POST'
          url: '#{chat_messages_path.html_safe}'
          data:
            chat_message: msg
            chat_room_id: chatRoomID
          dataType: 'json'
          success: ->
            scrollToBottom()
            $('input#chat_message_message').val ''
          fail: ->
            alert('Try again')
      return false

    $('input#chat_message_message').on 'input', (e) ->
      $('input.chat-input').toggleClass('disabled', e.target.value == "")

    $('form#new_prescription').on 'submit', (e) ->
      $('input#prescription_description').val ''
      $('#prescription').modal('hide')
    
    $('#send_transcript').on 'click', ->
      url = "#{doctor_chat_room_send_transcript_path(chat_room_id: '-chat-room-id').html_safe}"
      url.replace('-chat-room-id', "#{@chat_room.id}")
    
      $.ajax
        type: 'POST'
        url: url
        data:
          id: "#{@chat_room.id}"
        dataType: 'json'
        success: ->
          console.log('success')
        fail: ->
          console.log('fail')

:sass
  .margin-top
    margin-top: 5px


#user-id{"data-user-id" => "#{current_user.id}" }
#chat-room-id{"data-chat-room-id" => "#{@chat_room.id}"}

%br
.row
  .col-3
    .card
      .card-body
        %h5.card-title Related information
        %p.card-text
          %b Description:
          = @chat_room.request.description
        %p
          %b Patient:
          = @chat_room.patient.name

        - if @chat_room.request.media.attached?
          %p.card-text
            %b Attachment:
            = image_tag @chat_room.request.media.variant(resize: "200x200")

        %button.btn.btn-primary.margin-top#create-prescription{"data-target" => "#prescription", "data-toggle" => "modal",
          :type => "button"}
          Provide a prescription
          
        %button.btn.btn-info.margin-top#send_transcript
          Email transcript
  
        = link_to 'End Session', doctor_chat_room_end_session_path(chat_room_id: @chat_room.id),
          class: 'btn btn-danger margin-top', 'data-confirm': 'Are you sure you want to end the session?'

  .col-9.card
    .chat-room.card-body{"data-channel-subscribe" => "chat-room",
      "data-chat-room-id" => "#{@chat_room.id}", style: 'padding:0'}
      #chat_messages
        - @chat_messages.each do |chat_message|
          - if chat_message.user == current_user
            = render 'chat_messages/mine', chat_message: chat_message
          - else
            = render 'chat_messages/theirs', chat_message: chat_message
      .chat-box
        = simple_form_for @chat_message, remote: true do |form|
          .input-group.mb-3
            = form.input :message, as: :string, wrapper: false, label: false, placeholder: 'Type your message here...',
              input_html: { class: 'chat-input' }, include_blank: false, autocomplete: false
            .input-group-append
              = form.submit "Send", remote: true, class: 'btn btn-primary chat-input'
          = form.input :chat_room_id, as: :hidden

.d-none{"data-role" => "chat-message-template"}
  .chat-message-container
    .row.no-gutters
      .col-auto.text-center
        %img.avatar{alt: "", "data-role" => "user-avatar", src: ""}/
      .col
        .chat-message-content
          %p.mb-1{"data-role" => "chat-message-text"}
          .text-right
            %small{"data-role" => "chat-message-date"}

#prescription.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel",
  :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Provide a prescription
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %p You may choose to provide a prescription for the patient. Please be as specific as possible.
        .prescription-form
          = simple_form_for Prescription.new, remote: true do |form|
            .input-group.mb-3
              = form.input :description, as: :text, wrapper: false, label: false, include_blank: false,
                placeholder: 'Type your prescription here...', input_html: { class: 'description-input' },
                autocomplete: false, maxlength: 400
            .input-group-append{style: 'float:right'}
              = form.submit "Create", remote: true, class: 'btn btn-primary'
            = form.input :doctor_id, as: :hidden, input_html: { value: @chat_room.doctor.id }
            = form.input :patient_id, as: :hidden, input_html: { value: @chat_room.patient.id }