config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :users do
    get 'patients/register', to: 'patients/patient_registration#new', as: 'patient_registration'
    post 'patients/register', to: 'patients/patient_registration#create'

    get 'doctors/register', to: 'doctors/doctor_registration#new', as: 'doctor_registration'
    post 'doctors/register', to: 'doctors/doctor_registration#create'

    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :chat_messages
  resources :practices

  resources :doctors do
    get :search, on: :collection
  end

  resources :license_activations
  resources :prescriptions, controller: 'prescriptions'

  resources :patients do
    get :dashboard, to: 'patients#dashboard', as: 'dashboard'
    get :profile
    get :connect_with_doctor, to: 'patient_chat_rooms#connect_with_doctor'

    resources :chat_rooms do
      post :send_transcript, to: 'patient_chat_rooms#send_transcript'
      get :end_session, to: 'patient_chat_rooms#end_session'
    end
    resources :questions
    resources :transcripts, controller: 'patients/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'consultation_requests'
    resources :urgent_requests, controller: 'urgent_requests' do
      get :wait_screen
      get :check_for_session_start
    end
    root to: 'patients#index'
  end

  resources :doctors do
    get :dashboard, to: 'doctors#dashboard', as: 'dashboard'
    get :accept_urgent_request, to: 'doctors#accept_urgent_request', as: 'accept_urgent_request'
    get :profile
    get :connect_with_patient, to: 'doctor_chat_rooms#connect_with_patient'

    resources :chat_rooms do
      post :send_transcript, to: 'doctor_chat_rooms#send_transcript'
      get :end_session, to: 'doctor_chat_rooms#end_session'
    end
    resources :transcripts, controller: 'doctors/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'doctors/consultation_request'
    root to: 'doctors#index'
  end

  namespace :doctor do
    resources :answers
  end

  root to: 'static#index'
end

app/models/urgent_request.rb
class UrgentRequest < Request
  validates_length_of :description, minimum: 5, maximum: 1000
end

app/controllers/urgent_requests_controller.rb
class UrgentRequestsController < ApplicationController
  layout 'patients/patients'
  skip_before_action :verify_authenticity_token
  before_action :set_urgent_request, only: %i[show edit update destroy wait_screen check_for_session_start]
  before_action :set_patient

  def index
    @urgent_requests = UrgentRequest.where(patient: @patient)
  end

  def show
  end

  def new
    redirect_to root_path and return if @patient.in_session?
    @urgent_request = UrgentRequest.new
  end

  def create
    @urgent_request = UrgentRequest.new(urgent_request_params)
    @urgent_request.patient = current_user.patient

    respond_to do |format|
      if @urgent_request.save
        format.html do
          redirect_to(
            patient_urgent_request_wait_screen_path(urgent_request_id: @urgent_request),
            notice: 'Urgent Request was successfully created.'
          )
        end
        format.json { render :show, status: :created, location: @urgent_request }
      else
        format.html { render :new }
        format.json { render json: @urgent_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @urgent_request.update(urgent_request_params)
        format.html { redirect_to patient_urgent_request_path(id: @urgent_request), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @urgent_request }
      else
        format.html { render :edit }
        format.json { render json: @urgent_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def wait_screen

  end

  def check_for_session_start
    if @urgent_request.status == 'in_progress'
      @chat_room = ChatRoom.find_by(urgent_request_id: @urgent_request.id)
      if @chat_room.present?
        respond_to do |format|
          format.html { render plain: '' }
          format.json do
            render(
              json: {
                address: patient_connect_with_doctor_path(
                  patient_id: @patient.id,
                  urgent_request_id: @urgent_request.id
                )
              },
              status: :ok
            )
          end
        end
      end
    else
      respond_to do |format|
        format.html { render plain: '' }
        format.json { render json: {}, status: :bad_request }
      end
    end
  end

  def destroy
    @urgent_request.destroy
    respond_to do |format|
      format.html { redirect_to root_path}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_urgent_request
    @urgent_request = UrgentRequest.find(params[:id].presence || params[:urgent_request_id].presence)

    nil unless @urgent_request.present?
  end

  def set_patient
    @patient = current_user.patient
  end

  # Only allow a list of trusted parameters through.
  def urgent_request_params
    params.require(:urgent_request).permit(:patient_id, :description, :media)
  end
end

app/helpers/urgent_requests_helper.rb
module UrgentRequestsHelper
end

app/views/urgent_requests/_form.haml
:coffee
  $ ->
    $('.custom-file input').change (e) ->
      files = []
      i = 0
      while i < $(this)[0].files.length
        files.push $(this)[0].files[i].name
        i++

      $(this).next('.custom-file-label').html files.join(', ')


= bootstrap_form_for @urgent_request, url: patient_urgent_requests_path do |f|
  - if @urgent_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@urgent_request.errors.count, "error")} prohibited this urgent_request from being saved:"
      %ul
        - @urgent_request.errors.full_messages.each do |message|
          %li= message
  .field
    = f.text_area :description, required: true
  .field
    = f.file_field :media, required: false
  .actions
    = link_to 'Back', 'javascript:history.back()', class: 'btn btn-info'
    = f.submit 'Get help', class: 'btn btn-danger'

app/views/urgent_requests/edit.haml
:coffee
  $ ->
    $('.custom-file input').change (e) ->
      files = []
      i = 0
      while i < $(this)[0].files.length
        files.push $(this)[0].files[i].name
        i++

      $(this).next('.custom-file-label').html files.join(', ')

= form_for @urgent_request, url: patient_urgent_request_path do |f|
  - if @urgent_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@urgent_request.errors.count, "error")} prohibited this urgent_request from being saved:"
      %ul
        - @urgent_request.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :Media
  .field
    = f.file_field :media, required: false
  .field
    = f.label :Description
  .field
    = f.text_area :description, required: true
  .actions
    = f.submit 'Edit urgent request', class: 'btn-primary'
  .field



    = link_to 'Back', 'javascript:history.back()'

app/views/urgent_requests/index.haml
%h1 Listing urgent_requests

%table.table.table-hover
  %thead
    %tr
      %th Patient
      %th Description
      %th
      %th
      %th

  %tbody
    - @urgent_requests.each do |urgent_request|
      %tr
        %td= urgent_request.patient
        %td= urgent_request.description
        %td= link_to 'Show', urgent_request
        %td= link_to 'Edit', edit_patient_urgent_request_path(urgent_request)
        %td= link_to 'Destroy', urgent_request, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Urgent request', new_patient_urgent_request_path(@patient)

app/views/urgent_requests/new.haml
%h1 Get urgent help

= render 'form'

app/views/urgent_requests/show.haml
%h1 Your urgent request
%p
  %b Description:
  = @urgent_request.description
%p
  %b Attachment:
  - if @urgent_request.media.attached?
    = image_tag @urgent_request.media.variant(resize: "400x400")
  - else
    No attachments provided
= link_to 'Edit', edit_patient_urgent_request_path(@urgent_request)
= link_to 'Back', 'javascript:history.back()'

app/views/urgent_requests/wait_screen.haml
:coffee
  $ ->
    checkForSessionStart = ->
      $.ajax(
        url: "#{patient_urgent_request_check_for_session_start_path(urgent_request_id: @urgent_request.id)}"
        method: 'GET'
        dataType: 'JSON'
        data:
          urgent_request_id: "#{@urgent_request.id}"
        ).fail(->
          setTimeout(checkForSessionStart, 1000)
          console.log('Session has not started yet')
        ).done((data) ->
          window.location = data.address;
        )
      
    checkForSessionStart()

%h1 Please wait while we connect you to a doctor
%p
  %b Description:
  = @urgent_request.description
%p
  %b Attachment:
  - if @urgent_request.media.attached?
    = image_tag @urgent_request.media.variant(resize: "400x400")
  - else
    No attachments provided

= link_to "I don't need help anymore", patient_urgent_request_path(id: @urgent_request),
  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'