config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :users do
    get 'patients/register', to: 'patients/patient_registration#new', as: 'patient_registration'
    post 'patients/register', to: 'patients/patient_registration#create'

    get 'doctors/register', to: 'doctors/doctor_registration#new', as: 'doctor_registration'
    post 'doctors/register', to: 'doctors/doctor_registration#create'

    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :chat_messages
  resources :practices

  resources :doctors do
    get :search, on: :collection
  end

  resources :license_activations
  resources :prescriptions, controller: 'prescriptions'

  resources :patients do
    get :dashboard, to: 'patients#dashboard', as: 'dashboard'
    get :profile
    get :connect_with_doctor, to: 'patient_chat_rooms#connect_with_doctor'

    resources :chat_rooms do
      post :send_transcript, to: 'patient_chat_rooms#send_transcript'
      get :end_session, to: 'patient_chat_rooms#end_session'
    end
    resources :questions
    resources :transcripts, controller: 'patients/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'consultation_requests'
    resources :urgent_requests, controller: 'urgent_requests' do
      get :wait_screen
      get :check_for_session_start
    end
    root to: 'patients#index'
  end

  resources :doctors do
    get :dashboard, to: 'doctors#dashboard', as: 'dashboard'
    get :accept_urgent_request, to: 'doctors#accept_urgent_request', as: 'accept_urgent_request'
    get :profile
    get :connect_with_patient, to: 'doctor_chat_rooms#connect_with_patient'

    resources :chat_rooms do
      post :send_transcript, to: 'doctor_chat_rooms#send_transcript'
      get :end_session, to: 'doctor_chat_rooms#end_session'
    end
    resources :transcripts, controller: 'doctors/transcripts' do
      get :generate_transcript
    end
    resources :consultation_requests, controller: 'doctors/consultation_request'
    root to: 'doctors#index'
  end

  namespace :doctor do
    resources :answers
  end

  root to: 'static#index'
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user, optional: true
  has_many :questions, foreign_key: 'created_by_id'
  has_many :requests
  has_many :chat_rooms
  has_many :prescriptions

  def name
    user.username
  end

  def in_session?
    @active_urgent_request = UrgentRequest.find_by(patient: self, status: :in_progress)
    @active_consultation_request = ConsultationRequest.find_by(patient: self, status: :in_progress)

    @active_urgent_request.present? || @active_consultation_request.present?
  end

  def current_session_path
    @active_urgent_request = UrgentRequest.find_by(patient: self, status: :in_progress)
    @active_consultation_request = ConsultationRequest.find_by(patient: self, status: :in_progress)

    if @active_urgent_request.present?
      Rails.application.routes.url_helpers.patient_connect_with_doctor_path(
        patient_id: id,
        urgent_request_id: @active_urgent_request&.id
      )
    elsif @active_consultation_request.present?
      Rails.application.routes.url_helpers.patient_connect_with_doctor_path(
        patient_id: id,
        consultation_request_id: @active_consultation_request&.id
      )
    end
  end
end

app/controllers/patients/patient_registration_controller.rb
class Patients::PatientRegistrationController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :nuke_doctor_registration_session_var

  def new
    session[:creating_patient] = true
    session.delete :doctor_id
    redirect_to new_user_registration_path
  end

  private

  def nuke_doctor_registration_session_var
    session.delete(:doctor_id)
  end
end

app/controllers/patients/transcripts_controller.rb
class Patients::TranscriptsController < PatientsController
  before_action :set_transcript, only: [:show, :generate_transcript]

  def index
    @transcripts = Transcript.joins(:chat_room).where(chat_rooms: { patient: current_user.patient })
  end

  def set_transcript
    @transcript = Transcript.find(params[:id].presence || params[:transcript_id].presence)
  end

  def generate_transcript
    TranscriptMailer.with(transcript: @transcript, send_to: 'patient').chat_transcript.deliver_now
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  layout 'patients/patients'

  before_action :load_patient

  def dashboard
    @upcoming_consultations =
      ConsultationRequest
        .left_outer_joins(:chat_room)
        .where(patient: @patient, chat_rooms: { consultation_request_id: nil })

    @unanswered_questions =
      Question
        .left_outer_joins(:answer)
        .where(created_by: @patient, answers: { question_id: nil })
  end

  def index
  end

  def show
  end

  def profile
  end

  def edit
  end

  private

  def load_patient
    @patient = Patient.find_by(user: current_user)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/patients/_navbar.haml
:coffee
  $ ->
    $('#company-name, #company-logo').on 'click', ->
      window.location.href = '/'
      
    if "#{current_user.patient.in_session?}" == 'true'
      $('#UrgentHelp').attr('data-content', 'You cannot join another session as you are currently in one.')
      $('#UrgentHelp').attr('data-toggle', 'popover')
      $('#UrgentHelp').attr('data-type', 'button')
      $('#UrgentHelp').attr('data-trigger', 'hover')
      $('#UrgentHelp').attr('href', '#');
      

:sass
  #UrgentHelp
    margin-top: 4px
    margin-right: 10px

  .in-session-alert
    margin-left: 30vw

  #company-logo
    margin: 5px
    cursor: pointer

  #company-name
    margin-left: 10px
    cursor: pointer

%nav.navbar.navbar-expand-lg.navbar-light.bg-light.border-bottom
  = image_tag 'logos/favicon-32x32', id: 'company-logo'
  #company-name
    %b E-Health
  
  - if current_user.patient.in_session? && !request.path.include?('/connect_with_doctor')
    .in-session-alert
      = link_to 'You are currently in a session with a doctor', current_user.patient.current_session_path

  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto.mt-2.mt-lg-0
      %li.nav-item
        = link_to 'Seek urgent help', new_patient_urgent_request_path(current_user.patient),
          class: 'btn btn-danger', id: 'UrgentHelp'

      .dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true",
         "data-toggle" => "dropdown", href: "#", role: "button"}
          %img.avatar{src: "#{current_user.gravatar_url}"}
          = current_user.username
        .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
          = link_to 'Profile', patient_profile_path(current_user.patient), class: 'dropdown-item'
          = link_to 'Logout', destroy_user_session_path, class: 'dropdown-item'

app/views/layouts/patients/_sidebar.haml
:coffee
  $ ->
    found = false

    if window.location.pathname.indexOf('consultation_requests') >= 0
      $('#consultation-request-item').addClass('on-page')
      found = true

    if window.location.pathname.indexOf('questions') >= 0
      $('#question-item').addClass('on-page')
      found = true

    if window.location.pathname.indexOf('prescriptions') >= 0
      $('#prescription-item').addClass('on-page')
      found = true

    if window.location.pathname.indexOf('transcripts') >= 0
      $('#transcript-item').addClass('on-page')
      found = true
      
    if !found then $('#home-item').addClass('on-page')

:sass
  .on-page
    font-weight: bold


#sidebar-wrapper.bg-light
  .list-group.list-group-flush
    = link_to 'Home', root_path, class: 'list-group-item list-group-item-action bg-light', id: 'home-item'
    = link_to 'Consultations', patient_consultation_requests_path(current_user.patient),
      class: 'list-group-item list-group-item-action bg-light', id: 'consultation-request-item'
    = link_to 'Questions', patient_questions_path(current_user.patient),
      class: 'list-group-item list-group-item-action bg-light', id: 'question-item'
    = link_to 'Prescriptions', prescriptions_path(patient_id: current_user.patient.id),
      class: 'list-group-item list-group-item-action bg-light', id: 'prescription-item'
    = link_to 'Transcripts', patient_transcripts_path(patient_id: current_user.patient.id),
      class: 'list-group-item list-group-item-action bg-light', id: 'transcript-item'

app/views/layouts/patients/patients.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E Healthcare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    = render partial: 'shared/common_body_content'
    
    .page#container
      .header.no-print#header
        - if user_signed_in?
          = render partial: 'layouts/patients/navbar'
        - else
          = render 'shared/navigation_bar'
          = yield :header
      
      .d-flex#wrapper
        - if user_signed_in?
          = render partial: 'layouts/patients/sidebar'
        .col-8.col-md-10
          = yield